### ISSUE TITLE
Spaces in path break installation

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/m269-installer#12]
From an error reported by a tutor, it seems a space in the M269 folder path (e.g. when using OneDrive) causes the Windows `m269-23j` alias to think there are extra arguments in the command line. 

Need to replicate error on Windows and Unix to confirm spaces are an issue. If so, make sure the scripts / aliases handle such path names. Might be as easy as putting " around the path name?

**Comment by mwermelinger** [comment]
In macOS, if M269 folder path has space, the script exits with error that folder <name up to first space> doesn't exist.

**Comment by densnow** [comment]
"Quoting" $FOLDER and using double square brackets in the first if statement (inside `is_m269_folder`) means that paths with spaces are recognized  as directories. E.g.
```bash
# install.sh line 54
if [[ ! -d $1 ]]
# install.sh line 77
is_m269_folder "$FOLDER"
```
A further set of quotes is needed around the $1 argument when using basename . E.g.
```bash
# install.sh line 57
elif [[ $(basename "$1") != [Mm]269-23[Jj] ]]
```
The script runs after this, but the issue reoccurs for the aliases. However, adding some escaped quotes appeared to fix the problem.
```bash
M269="cd \"$FOLDER\";source $VENV/bin/activate"
NB="jupyter notebook \"$FOLDER\"&"
ALLOWED="python3.10 \"$FOLDER/allowed.py\" -c \"$FOLDER/m269.json\"" 
```
Maybe something similar could work on Windows, but I have already had my recommended daily dose of Windows today :smile:

**Comment by mwermelinger** [comment]
Many thanks! I've committed your suggestions. @DanielVernall @cameron-s-scott would one of you be willing to fix and test the Windows script for folder names with spaces?
