### ISSUE TITLE
Code "blocks" instead of "inline" code in instructions (README), for faster copy paste

### ISSUE THREAD

**Issue by densnow** [dsa-ou/m269-installer#16]
Code in written in "blocks" (delimited by ``` in md) allows it to be copied with one click (the box in the top right corner) as opposed to selecting with mouse. E.g.

try to copy `this command -h -e -r -e` vs
```text
this command right -h -e -r -e
```
it is certainly not a big deal , but this could make things a little easier during the install process. Maybe a mention of the "click to copy" box could be mentioned in the instructions.

**Comment by mwermelinger** [comment]
Are you sure that works in the generated GitHub Pages, i.e on https://dsa-ou.github.io/m269-installer?

**Comment by densnow** [comment]
To be honest I had not considered that! 

I have just looked at a couple examples and it looks like it does _not_ carry through :frowning_face:  (annoying because [readthedocs](https://readthedocs.org/) _does_ keep the boxes). 

Doing this would only benefit the normal Github Project page and so may not be worth the effort and potential downgrade in "style". Any mention of a "click to copy" box could certainly confuse things so we can throw that out of the window!

**Comment by mwermelinger** [comment]
OK, closing with won't do.
