### ISSUE TITLE
Test on WSL

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/m269-installer#2]
The instructions need to be tested and possibly modified for Windows. As I don't have Windows, this requires input from others.

1. Please follow the [software installation instructions](https://dsa-ou.github.io/m269-installer) and make a note of anything that is unclear, missing, unexpected (behaved differently from what the instructions say) or not working, as you install the WSL and the M269 software on your Windows system. 
2. After installing the software (Section 2 of the instructions), download the book from the M269 site into the M269 folder you created. Then proceed with Section 3 of the instructions to check the software is working. Note anything that is unclear or not working.
3. Post a comment below, indicating what Windows version you used and whether everything went fine or what problems you encountered. In particular, let us know if you put your M269 folder in WSL or in Windows (e.g. `/mnt/c/Users/...`).

Many thanks!

**Comment by cameron-s-scott** [comment]
Hi Michel,

I have begun the process of downloading the m269 software using the WSL system on Windows 11. 

My first installation of the software seemed to finish successfully but as i moved on i realised there was an issue. I noticed there was a message prompting me to install the package `python3.10-venv`, so i followed the advice by entering `sudo apt install python3.10-venv`. I then went back to the installation steps and installed the software again which was successful.

Or so it seemed, as i was able to enter the M269 folder and the command prompt line became `(m269-23j)...`. However, when i tried to access the notebooks i received this error:
`ls: cannot access '/home/cameronscott/OU/M269-23j/book-r*': No such file or directory
[C 20:32:48.146 NotebookApp] No such file or directory: /notebooks/M269.ipynb`

Below is a picture of the command prompt when it happened.
Cameron
![error-message 2045 2-6-23](https://github.com/dsa-ou/m269-installer/assets/135262741/0652f6f1-0b5c-46cb-9cf8-70ae4b1b1dfd)

**Comment by DanielVernall** [comment]
> I was then able to enter the M269 folder and the command prompt line became `(m269-23j)...`. However, when i tried to access the notebooks using `nb` i received this error:
> `ls: cannot access '/home/cameronscott/OU/M269-23j/book-r*': No such file or directory [C 20:32:48.146 NotebookApp] No such file or directory: /notebooks/M269.ipynb`

Hi Cameron,

It looks like you haven't downloaded the notebook yet. Here's the relevant bit from the instructions:
<img width="638" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/df5bd3d1-c412-4e82-9815-dbf467431957">

You should have these files/folders in the M269-23J folder:
<img width="324" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/f68e08d8-42b4-4578-bf1d-3247a6a7ff75">

To copy the book in, just run file explorer from the WSL terminal and copy in the folder from Windows:
<img width="789" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/f39e8ecc-48f6-424c-8c21-b377b667be2c">

**Comment by DanielVernall** [comment]
After you've added the book folder run `nb` and you'll see this:
<img width="944" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/8574cc40-eff6-4a19-8158-68ba3255224b">

Then control+click on one of the links at the bottom (eg. http://localhost....) to open the notebooks in your browser

**Comment by DanielVernall** [comment]
@mwermelinger I get permissions errors when opening the notebooks, so they are read only:
<img width="653" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/33fe1703-1e05-4dae-9540-4cd29c8bae50">

<img width="777" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/ed82ad63-a9fa-4e74-bc11-e27a96407850">

I believe this is to do with copying files from Windows to WSL via explorer.exe

**Comment by DanielVernall** [comment]
Yeah, you have to copy in the files via the WSL terminal to avoid the permissions issues:
<img width="737" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/e8f4a41b-f7dd-4a68-8b9d-ea2d5fdfd904">

<img width="800" alt="image" src="https://github.com/dsa-ou/m269-installer/assets/6403967/3e56628e-d749-402c-8621-db892a759f66">

Although, to be honest this install process on Windows actually seems more involved than the Anaconda one we used in 22J...

**Comment by cameron-s-scott** [comment]
Hi Daniel, well it is ironic that the sentence i missed starts with "Obviously"! 

Thank you for pointing this out.

I think it could be an idea to add this as an instruction before the use of the software. As downloading and installing the M269 book is part of the installation process after all.

**Comment by cameron-s-scott** [comment]
I finally got the notebooks to work. Thank you Daniel for pointing out my _**obvious**_ overlook!

Could we create a clearer instruction for putting the notebooks in the M269 folder? The instruction could be added into the installation section of the instruction guide and could look something like this:

_1. To access the notebooks, you will need to download the M269 book from the resources tab on the M269 site and install it into the folder you have created._

I completed the installation process on Windows 10 and i encountered a different issue when trying to install WSL. The command prompt indicated that i did not have virtualisation enabled which seems to be the default option.

This required turning the SVM feature _(i think its GVT for Intel)_ on in my BIOS and enabling Hyper -V in my Windows optional features, which was simple enough to do but it added a bit of complexity to the installation process.

**Comment by mwermelinger** [comment]
Cameron, Daniel, many many thanks for trying it out and all the feedback! Apologies for not replying sooner.

I'll make the instructions about installing the notebooks clearer, as an explicit step.

- @cameron-s-scott , at what point were you asked to install python3.10-venv? Does Python 3.10 for WSL not include the venv module? That's odd...
- @DanielVernall Doesn't the `nb` command automatically open the browser with the cover notebook?
- @DanielVernall Did you also have to enable virtualisation, like Cameron?
- @cameron-s-scott If I understood correctly, virtualisation has to be enabled before installing WSL. Correct? What are the exact steps to enable virtualisation?
- @both Where is your M269 folder? In Windows or in WSL? Does the read-only issue only occur with one of them?
- @both Do you have to type your password after each `wsl` command?

It seems that if we iron out these issues to make instructions for Windows clearer, then we'll have the same environment for everyone and equal to JupyterHub, at the expense that installing WSL is a bit more hassle than installing Anaconda. Thanks again.

**Comment by mwermelinger** [comment]
Forgot to ask: which exact Windows versions did you use? And have you run a couple of notebook cells to check if it was working?

One addendum: 

I think it may be better if the M269 folder is in the Windows filesystem so that the folder can be in a cloud drive and so that the PDF and HTML versions of the book can be accessed without going through WSL. Would you agree?

**Comment by cameron-s-scott** [comment]
Hi Michel, apologies for the late reply i have been away on holiday!

### Windows versions of the pc's i used:

- **Laptop**: Windows 11 version 22H2 with OS build 22621.1778
- **Desktop**: Windows 10 Pro version 22H2 with OS build 19045.3086

I have opened the notebooks and worked through a couple of sections to make sure they were working ok. I had no issues when using the notebooks but the only issue i can see is that the `nb` command does not automatically open the notebooks, i had to copy the link into my browser and open them from there.

### Venv issue:

**NOTE:** This issue only occurs on my laptop that uses Windows 11.

I had to install the venv package when trying to install the `m269.sh` file. I found it weird as well, i would have though python3.10 would come with it. I have done the installation process twice on Windows 11 though and had the same prompt! 

### Virtualisation issue

As soon as i tried to install WSL i was prompted to enable Virtualisation and Hyper -V, the steps to do so are as follows:
  
**NOTE:** This only occured on my desktop when installing on Windows 10.

### Enable Virtualisation in BIOS

1. Restart your computer, entering the BIOS access key when prompted on startup.
2. Enter advanced mode by entering `F7` or clicking on it in the bottom right corner.
3. Navigate to the Advanced tab in this mode.
4. Scroll down and select CPU configuration.
5. Find the "SVM" (AMD) or "Intel Virtualisation Technologies" (Intel) feature and enable it in the drop down menu next to it.
6. Lastly, click on Exit and OK to save the changes made.

**NOTE**: The nomenclature may change with different laptop/desktop models and configurations.

### Enable Hyper -V which i did through Windows settings:

1. Right click on the Windows button and select ‘Apps and Features’.
2. Select Programs and Features on the right under related settings.
3. Select Turn Windows Features on or off.
4. Select Hyper-V and click OK.

![image](https://github.com/dsa-ou/m269-installer/assets/135262741/728d62bd-6f7b-4071-9292-3ecd9fb8358f)

When the installation has completed you are prompted to restart your computer.

### WSL folder location
I have the M269 folder in the WSL file system and had no read only issues. Trying to install the M269 folder in the Windows file system but it seems to keep finding itself in WSL. Feeling a little bit silly and think i may be missing something! 
I agree that having the folder in the Windows filesystem would be the best option because it can be backed up in a cloud drive, as you said.

**Comment by densnow** [comment]
@cameron-s-scott , @mwermelinger on Windows 10 running WSL version 1 in virtualbox, I had the same `venv` issues. It seems like the default installation of Ubuntu (used by WSL) does not have this package or has an outdated version.

I would recommend either adding a new instruction for WSL users to `sudo apt update; sudo apt upgrade` their fresh install (obviously only if using a Debian based distro) then `sudo apt install python3.10-venv` or somehow testing for a Debian based distro and incorporating it into the script.

RE browser not automatically opening Jupyter notebooks: I was also having the same issue and managed to get around  it by using  `wslu` ([link here](https://github.com/wslutilities/wslu)) and setting the `BROWSER` environment variable. `wslu` is a collection of WSL utilities and is available via the standard package manager (apt) in Ubuntu. A useful thing to find out would be if it was really necessary to set the `BROWSER` environment variable in addition to installing `wslu`. I did them both at the same time which worked then subsequently removed the environment variable and it still worked, but I am not 100% sure it will work without setting the variable.

`wslu` can be installed with
```bash
sudo apt install wslu
```
and the environment variable can be set permanently by adding
```bash
export BROWSER=wslview
```
To your `~/.bashrc` file

If someone could try  installing `wslu` before setting the variable and see if it still works, I think that could be useful.

**Comment by mwermelinger** [comment]
@cameron-s-scott @densnow Many thanks both for your detailed answers and investigations! Must have taken quite some time.

I'm starting to think, from your reports, that installing and using WSL is more hassle (and occupies more disk space) than it's worth. The main reason is that `allowed -m` requires `pytype`, which only works on Unix. However, the JupyterHub installation will be on Unix and will have `pytype` and `allowed`, so students on Windows users can always use the JupyterHub to check their TMAs. I'll open a new issue for a different kind of installation for Windows.

**Comment by DanielVernall** [comment]
@mwermelinger,

Sorry I've not been able to respond recently, I've been busy with a personal code project.

You may be interested in creating a docker container for M269. These can https://docs.docker.com/desktop/wsl/[run on WSL2 in Windows.](https://docs.docker.com/desktop/wsl/)

**Comment by mwermelinger** [comment]
@DanielVernall Thanks, but from the link you give it seems the students would still have to install WSL before installing Docker to then install the M269 image, so I'm not sure what would be the advantage, but I may have got the wrong end of the stick.

**Comment by mwermelinger** [comment]
Thanks for the clarification. I don't think that the problem is with installing the Python environment, because the script does that automatically, it's installing WSL (and hypervisor and wslu...) that is the faff and adding Docker to it doesn't seem to reduce the work.

**Comment by mwermelinger** [comment]
Closing this as I think it's not justifiable to require WSL just to support `allowed -m`. Many thanks everyone for your feedback and time!
