### ISSUE TITLE
Space in username on windows causes aliases to fail

### ISSUE THREAD

**Issue by densnow** [dsa-ou/m269-installer#27]
The title pretty much says it all. This could possibly be fixed by changing line [98](https://github.com/dsa-ou/m269-installer/blob/e9288e0c63b3b8d5b829e616d61f77e61bae84ac/install.ps1#L98) in install.sh to:
```powershell
& '$VENV\Scripts\Activate.ps1'
```

**Comment by densnow** [comment]
We might need to add quotes to any lines that use `$VENV`, namely [83](https://github.com/dsa-ou/m269-installer/blob/e9288e0c63b3b8d5b829e616d61f77e61bae84ac/install.ps1#L83) and [86](https://github.com/dsa-ou/m269-installer/blob/e9288e0c63b3b8d5b829e616d61f77e61bae84ac/install.ps1#L86)

**Comment by densnow** [comment]
After minimal testing it looks like only line 98 needs to be changed. When `$VENV` is used as arg or with . (dot) in front of path it seems to be protected against spaces in the path.

**Comment by mwermelinger** [comment]
Thanks, please do a PR.
