### ISSUE TITLE
macOS: sometimes `~/.bash_profile` is sourced instead of `~/.bashrc` on terminal startup

### ISSUE THREAD

**Issue by densnow** [dsa-ou/m269-installer#37]
There have been two reported instances of macOS not sourcing `~/.bashrc` on terminal start up. One of these was resolved by appending 
```bash
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
```
to `~/.bash_profile`.

[This document](http://hayne.net/MacDev/Notes/unixFAQ.html#shellStartup) is often posted in response to queries dealing with this topic. It details which startup files are used and the order they will be read by the shell including `bash`.

There might be an option inside of macOS to change the type of shell that is opened from "login shell" to "non-login shell", and hence source the `~/.bashrc` by default. But this could have more implications to the system than checking for and appending the above code to the appropriate file.

**Comment by densnow** [comment]
Instead of modifying and overcomplicating the script for this potentially rare error, maybe it could be mentioned briefly  at the end of the installation instructions.

The students who encountered this problem had run the script with no obvious errors or warnings being shown, but when they tried to use the aliases `m269-23j` and `nb` nothing happened. A quick fix is to enter the following command:
```bash
echo 'if [ -f ~/.bashrc ]; then source ~/.bashrc; fi' >> ~/.bash_profile
```

**Comment by mwermelinger** [comment]
I agree it's best to add to installation instructions than changing the script. Could you open a PR with that?Thanks.
