### ISSUE TITLE
Install script creates shell alias incorrectly

### ISSUE THREAD

**Issue by azero-dev** [dsa-ou/m269-installer#44]
When the install script creates the alias in the shell (zshrc), it does so without creating a line break, so it concatenates with the previous text. This causes an error because it does not create the alias correctly, and also disables the previous text.

For more information, this happened on a machine with Manjaro Linux using zsh shell.

And of course, thanks for the script!

**Comment by mwermelinger** [comment]
Strange because it works on macOS zsh. My only hypothesis is that the echo command in Manjaro does not add a newline by default. Not sure how to best do this to work for all Unixes.

**Comment by azero-dev** [comment]
In that case, perhaps a warning in the instructions would be sufficient? The solution is as simple as going to the zshrc file and adding the line break, so if a warning is given it will avoid confusion for future students.

**Comment by mwermelinger** [comment]
Thanks for the suggestion. Will keep this issue open so that we address it when doing the 25J script.

**Comment by azero-dev** [comment]
I just asked ChatGPT how to create the line break (I have no experience with bash scripting) and it gave me the following code. If it helps I can test it on a virtual machine.

`# Ensure the shell config file ends with a newline before appending
if [ "$(tail -c1 "$FILE")" != "" ]; then
    echo >> "$FILE"
fi

# Now add the aliases
echo "alias $COURSE=\'$M269\'" >> $FILE
echo "alias nb=\'$NB\'" >> $FILE
`

**Comment by mwermelinger** [comment]
Ah, I didn't notice the "concatenates to the previous text" in your original message. So the problem has nothing to do with zsh. If the shell file (whichever it is) doesn't end in a newline, then the first alias (m269-24j) will be joined to whatever is in the last line of the file. The solution is indeed to simply do `echo >> $FILE` beforehand, no need to check the tail of the file. If there's already a newline, there will be a blank line before the M269 aliases, which is fine.

If you're comfortable with changing the modified install.sh script on your machine and do a pull request, I can then ask Michael, who's also on Linux, to test the PR.

**Comment by azero-dev** [comment]
Sure! I'll do it now.
