### ISSUE TITLE
Check M269 folder exists

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/m269-installer#5]
Students will start in the VLE, where they are told to create their M269 folder, download and unzip the book there, and start reading it. Only afterwards do they get to the software installation instructions. So the script should check that the argument corresponds to an existing folder with base name `m269-23j` or `M269-23J`  and has a subfolder for the book. This will allow the student to immediately start using the notebook after installation.

- Change README to make clear the M269 folder and the book must already be installed.
- Change script to check for folder.
- Script may also nudge user to install TMAs if their subfolders don't exist.

**Comment by densnow** [comment]
I have a couple of thoughts not sure if they are useful so feel free to shoot them down :smile:

It seems kind of messy to have the user create the folder then use the path to said folder as argument only to check the existence of the folder again. Why not substitute the instruction to create the M269 folder on the VLE for an instruction to download unzip and run the software installation and have the installation handle folder creation (either with or without an argument). You would then need an instruction to navigate to the new folder, download and unzip the book, which I am assuming would be the instruction that is already there?

I always thought it would be great if the installer could also download and unzip the book in the correct location. Of course you can't have the URL to the book on this public repo. Just wondered if you had ever considered this and if there is a way to get around it (e.g. URL as argument, or additional private repo with correct URL)?
